{{ if   (.Files.Glob "config/*.yml") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peatio.fullname" . }}
  labels: 
    {{- include "peatio.labels" . | nindent 4 }}
    app.kubernetes.io/component: peatio
data:
{{- if (.Files.Glob "config/*.yml") }}
{{ (.Files.Glob "config/*.yml").AsConfig | indent 4 }}
{{- end }}
{{ end }}
