{{ if  ( (.Files.Glob "files/postgresql.conf") or (.Files.Glob "files/pg_hba.conf") )}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels: 
    {{- include "influxdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
data:
{{- if (.Files.Glob "files/postgresql.conf") }}
{{ (.Files.Glob "config/influxdb/build_candles.sql").AsConfig | indent 2 }}
{{- end }}
