apiVersion: {{ template "peatio.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "peatio.fullname" . }}
  labels:
    app: {{ template "peatio.name" . }}
    chart: {{ template "peatio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "peatio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "peatio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: peatio
        image: {{ .Values.peatio.image.repository }}:{{ .Values.peatio.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: 
        - bash -c "bin/link_config && bundle exec puma --config config/puma.rb"
        
        env:
          - name: RAILS_ENV
            value: production
          - name: RAILS_ROOT
            value: "/home/app"
          - name: PORT
            value: "8000"
          - name: URL_HOST
            value: "www.app.local"
          - name: LOG_LEVEL
            value: warn
          - name: ADMIN
            value: admin@barong.io
          - name: DATABASE_HOST
            value: db
          - name: DATABASE_PORT
            value: 3306
          - name: DATABASE_USER
            value: root
          - name: DATABASE_PASS
            value: changeme
          - name: VAULT_URL
            value: http://vault:8200
          - name: VAULT_TOKEN
            value: s.xr0SBStVuw8mOmAu7jbggDsd
          - name: REDIS_URL
            value: redis://redis:6379
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RANGER_HOST
            value: ws.ranger.wb.local
          - name: RANGER_PORT
            value: 80
          - name: MARKETS_CONFIG
            value: /opt/peatio/config/seed/markets.yml
          - name: CURRENCIES_CONFIG
            value: /opt/peatio/config/seed/currencies.yml
          - name: MANAGEMENT_API_V1_CONFIG
            value: /opt/peatio/config/management_api_v1.yml
          - name: JWT_AUDIENCE
            value: peatio,barong
          - name: JWT_PUBLIC_KEY
            value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1WGxkMXZreUYyQWkvL29mYlY5Uwp4UVBzMWw3dDY2YVdwSWRjY1VJNUNDRlhlc0V5VmNuS0ZzWHBWQUREdGZ4Q1ZsUkliaFpJaUo4OUVpeTJITjQvCjZYT0IvaW1GaXBaSm8xa2hZeUxFbHdIbWNxdHBCVys0K0NtRkdBMEE2Mll4VU5KT1hUN2RqOWxobTR1NzFDUHIKT2xJMUpLRXpWK2MwQklFKzh1R2RkMVB2VzA1UXJLTlFaSXlHejBOSWZuNXBMRVVKRmVFa2ZSdmJTaFBGQUFSSwprTENiMTAveWptNDdNcXlobnJhL2JvZWVxUUNJWHZpbWZmR1VFY3NVYXJranlkSHR5SzBlSVR4Qm9UVU9welhiCkx2ZHBaenlWcnlVR2lTaWFsa09wdStKT1Rpbkw1NUFBdmoyRDdiYmJOUFhqVjFoRTZWekgweFh6UVBUT2VMN0wKT1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
          - name: INFLUXDB_HOST
            value: influxdb
          - name: EVENT_API_JWT_PRIVATE_KEY
            value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdVhsZDF2a3lGMkFpLy9vZmJWOVN4UVBzMWw3dDY2YVdwSWRjY1VJNUNDRlhlc0V5ClZjbktGc1hwVkFERHRmeENWbFJJYmhaSWlKODlFaXkySE40LzZYT0IvaW1GaXBaSm8xa2hZeUxFbHdIbWNxdHAKQlcrNCtDbUZHQTBBNjJZeFVOSk9YVDdkajlsaG00dTcxQ1ByT2xJMUpLRXpWK2MwQklFKzh1R2RkMVB2VzA1UQpyS05RWkl5R3owTklmbjVwTEVVSkZlRWtmUnZiU2hQRkFBUktrTENiMTAveWptNDdNcXlobnJhL2JvZWVxUUNJClh2aW1mZkdVRWNzVWFya2p5ZEh0eUswZUlUeEJvVFVPcHpYYkx2ZHBaenlWcnlVR2lTaWFsa09wdStKT1RpbkwKNTVBQXZqMkQ3YmJiTlBYalYxaEU2VnpIMHhYelFQVE9lTDdMT1FJREFRQUJBb0lCQUUyRXN6ckpGaTE4NmNQdwp4emZRTW1qVGRpWTJzTnZmMlhCVWZzZDdkUmkzenJjb2ppQWE0WkxaRHVja0ZxZzJFWWZCWERCZXNkd2dLY2N4CjFyK0VDRlJMQ1phdnhmZWhUbyt1RGUxQU44Z2hiQzZiQTU3WkRnYnlXNFVzMGlpUW9xWHo3L3E2N3FGVHFwNzMKTFA3Q01HdEV0cDlqbkhEdDJlalVGL290WDhIaUphOE9XNXpIY0hDZmRabTBab1NlTlNEOXpNbmxTQU5CSGdQaQpHaWpaQVhOYlI4cXpxK0JrdTlUTTJjTUZSZjVUYWNQOU5CeGQwa2J6bXBDbUVKR0t6dVl6amw5S096RDd2Zng3CjFORm53ZlhoRUs1TDB4aWxZS2EwYVR6Z21OSzcxdmhuVVdiMURna3ltRGprU3VDL3ozbWJYLzRuOStZVDdEVmoKYTdqdE53RUNnWUVBMncvMVNuVHpiWTY2b05wblJYSW8zcE83ZEdyenR6azdLR3cyaC9UanJxQ3JrVGVYUzNpawpqaStCVjZmMDlRUUhsYUdCb2VTdDN3c2duK3hGMjZJc1BmOEhTaDlYeDNmVEVqQmNCbTR3b1ZPTzN4Nll1aHdEClJERWU4TWlZa3VUQWVBWnZVcG9SK01iR2xGTzdnOWxRSUtmM1ptb2x2MkFLWHNXVXRnSXpOTmtDZ1lFQTJMK0oKM0diUnNzYmQ5a2hibUF0S09iLzZrWGI5aFk5aVNpbHlBQ0ExOFkzY0dEM01LWGp4MEx6WHA0bmlMeXZOYmdVVgpyam95YXNQV3grWk1HS0NFY2REY3Z5c25wbTNVYzRHdzgveHp1ellDY25VQ3c1ajFuVlVhUEFvb2RnbDVQcThBCkllVWpjR2hKQmhmVkFXdDkrekovS2Vmcml6T1BBTEJIS0xaMnpXRUNnWUJnQWo5OE1ZT2E2YW9yNDJ6Tmgvb1gKaXVIbVpSV0pvUUNuZDczeW1rYkxlMG1XYktuWGZ2bUlBNVFKaWVnWEZud0lmVzltTitab1VlVXJrZzhQOHFTMwpTeld6cThiNStpODgwb3NTbW1xZjJoSk5BWWpvVUd5eUQyRkRJSGVXTWNHVkdTVGpLL2xpY2lRSVVDWm40KzkxClVJaGlqM1VaeWdyaGZIRHYwRWtIQ1FLQmdRQ1pWYTlXcjVwcjZnbitnQ1BrQlNDbWlDemdHWml5a3NRTENSVHcKQjltQm9FVHpGVXpJamhvci9GeG4xc0NmZEZKcEljbTdyc29hQTU5L1hXbTZCbHlNRkNFR1VLWkZNKytYSTBtbQo0WktSLzF4dDBsOTVOazJUMXkrdkI5U2w1SC9VbTRMeGQ2UEJrdFVPTFcvd0NEWmdyZEdPT05iR2JGd2ZOWld4CnRKdUpJUUtCZ0Fyci92UGlPdXViMVF0c2JQL0NaMEZaaHM5U3loNTY5ZDU2UmJDbldTb2pHSi83ZjZEM2xQMkkKaUpqSFNlRUZsQXhOb1JQbXN3WFg2WHN4cXpoaVFXNjJSamtvNTVJckJWdGFjQk9JNVd6bEV2QlRvZk9BOTcrWApTejlXN0d1SGdnbzVsMFowS0UzVThaQkNUajRVRjk5VW90L2s4YU94N2QrQnRIdTI1WkxlCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
          - name: EVENT_API_JWT_ALGORITHM
            value: RS256
          - name: EVENT_API_RABBITMQ_HOST
            value: rabbitmq
          - name: EVENT_API_RABBITMQ_PORT
            value: 5672
          - name: EVENT_API_RABBITMQ_USERNAME
            value: guest
          - name: EVENT_API_RABBITMQ_PASSWORD
            value: guest
          - name: MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT
            value: 1
          - name: MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW
            value: 3
          - name: MINIMUM_MEMBER_LEVEL_FOR_TRADING
            value: 2
          - name: SECRET_KEY_BASE
            value: faiba2shei0Ae5gahCh4aipoh3meyaFi
          - name: FORCE_SECURE_CONNECTION
            value: "false"
 

        volumeMounts:
          {{- if (.Files.Glob "config/plugins.yml") }}
            - name: peatio-plugins
              mountPath: /opt/peatio/config/plugins.yml
          {{- end }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        
     
      volumes:
        {{- if (.Files.Glob "config/plugins.yml") }}
        - name: peatio-plugins
          configMap:
            name: {{ include "peatio.configmapName" . }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
