imagePullPolicy: IfNotPresent

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

peatio:
  image:
    repository: quay.io/openware/peatio
    tag: 2.4.7





