apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ template "vault.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "vault.name" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: vault
    port: 8200
    protocol: TCP
