apiVersion: v1
appVersion: 3.7.6
description: Open source message broker software that implements the Advanced Message Queuing Protocol (AMQP)
engine: gotpl
home: https://www.rabbitmq.com
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
keywords:
- rabbitmq
- message queue
- AMQP
maintainers:
- email: h.soltani@khallagh.com
  name: SantoDE
name: rabbitmq
sources:
- https://github.com/bitnami/bitnami-docker-rabbitmq
version: 1.0.0
